### ISSUE TITLE
Feature Request World Boss + World Boss Event

### ISSUE THREAD

**Issue by dbzdivik** [tmarenko/mff_auto#9] opened 2020-10-12 05:13 UTC
1. World Boss Request
Option to Save Stage to be cleared based on boss
For Quicksilver Ultimate - 15
For Cable Ultimate - 10 so on

2. Option to Support World Boss Event Request 

3. What about Character Recognization Feature ??

**Comment by tmarenko** [comment] 2020-10-13 15:57
> Option to Save Stage to be cleared based on boss

Could be done, low priority though.

> Option to Support World Boss Event Request

Is it rare event with 3/3 daily World Boss Normal stages? Or World Event with 2/2 daily entries when you get Agent Kits?

> What about Character Recognization Feature ?

229 characters in the game + 273 uniform (changes character's look). Too much to maintain.

**Comment by dbzdivik** [comment] 2020-10-13 16:11
> > Option to Save Stage to be cleared based on boss
> 
> Could be done, low priority though.
>
OK
> > Option to Support World Boss Event Request
> 
> Is it a rare event with 3/3 daily World Boss Normal stages? Or World Event with 2/2 daily entries when you get Agent Kits?
> 
Hmm Yeah, waste of time and maintenance.

> > What about Character Recognization Feature ?
> 
> 229 characters in the game + 273 uniform (changes character's look). Too much to maintain.

Let me know if I could help. with anything

**Comment by jeisonfura** [comment] 2020-11-23 07:37
I want to help too. I've been looking over the code.

**Comment by tmarenko** [comment] 2021-07-24 11:29
> World Boss Request
Option to Save Stage to be cleared based on boss
For Quicksilver Ultimate - 15
For Cable Ultimate - 10 so on

Can you explain how this feature would have been working? Is it something like "set different difficulties for Today's World Boss"?

**Comment by dbzdivik** [comment] 2021-07-24 13:28
> > World Boss Request
> > Option to Save Stage to be cleared based on boss
> > For Quicksilver Ultimate - 15
> > For Cable Ultimate - 10 so on
> 
> Can you explain how this feature would have been working? Is it something like "set different difficulties for Today's World Boss"?

Basically Yest it was like Setting different Ultimate Level based on Team "Assuming If todays' WB is QuickSilver and I'm having only team 1 and Team 2 which can win level 30 pretty easy and other teams can win level 15,16 or so on.
 
But It was a pretty useless feature though & it can be skipped.
BTW I was thinking of closing this request coz of Character recognition is too bulky to maintain.

**Comment by tmarenko** [comment] 2021-07-24 13:32
> But It was a pretty useless feature though & it can be skipped.
BTW I was thinking of closing this request coz of Character recognition is too bulky to maintain.

If you think so then close it, sure. I've added World Boss Event in https://github.com/tmarenko/mff_auto/commit/c097f2690494eafce29c7ae9550bc19e4165925e and have no plans to implement character recognition.

**Comment by dbzdivik** [comment] 2021-07-24 13:56
Event Boss Raid is working fine Great.

Reopening issues just for your review regarding Support team Selection in WB and EBR, Like team 1 is selected the Supporting team 1 is selected and so on.

**Comment by tmarenko** [comment] 2021-08-13 16:57
> Support team Selection in WB and EBR, Like team 1 is selected the Supporting team 1 is selected, and so on.

Added in https://github.com/tmarenko/mff_auto/commit/588244a1de8458468304486db50b2b68fdb98e4d
![image](https://user-images.githubusercontent.com/31345208/129393539-fe835ebf-2ec0-49ae-8d4f-5fa89008aca9.png)

Should select character and allies team with the same number. However this should work only if you had full 5/5 stage of World Boss. Otherwise it might select already used team but I'm not sure should I check for this or not

**Comment by dbzdivik** [comment] 2021-08-14 04:01
Cool thanks. Will let you know

**Comment by tmarenko** [comment] 2021-08-21 20:36
@dbzdivik any luck with this changes?

**Comment by dbzdivik** [comment] 2021-08-22 11:25
> @dbzdivik any luck with this changes?

Hi Sorry, lacking some time to try out this feature. Will update you soon.
Thanks again

**Comment by dbzdivik** [comment] 2021-08-24 03:43
I think WB is broken

`2021-08-24 09:11:45,501 - DEBUG - queue_manager - Running WORLD BOSS with settings: {'mode': 'ULTIMATE', 'boss': 'TODAYS_BOSS', 'difficulty': 5, 'sync_character_and_ally_teams': True}
2021-08-24 09:11:46,398 - DEBUG - root - Creating 4 Tesseract API(s) with 'eng' language.
2021-08-24 09:11:46,706 - DEBUG - root - Creating 2 Tesseract API(s) with 'mff+eng' language.
2021-08-24 09:11:50,643 - ERROR - game - Failed to open Content Status board.
2021-08-24 09:11:50,748 - DEBUG - queue_manager - Queue completed.
2021-08-24 09:11:55,641 - DEBUG - queue_manager - Running queue.
2021-08-24 09:11:55,642 - DEBUG - queue_manager - Skipping queue item: DAILY TRIVIA
2021-08-24 09:11:55,644 - DEBUG - queue_manager - Skipping queue item: DISPATCH MISSION: ACQUIRE ALL REWARDS
2021-08-24 09:11:55,645 - DEBUG - queue_manager - Skipping queue item: WORLD BOSS INVASION
2021-08-24 09:11:55,649 - DEBUG - queue_manager - Skipping queue item: ALLIANCE BATTLE
2021-08-24 09:11:55,653 - DEBUG - queue_manager - Skipping queue item: PLAYING HERO
2021-08-24 09:11:55,654 - DEBUG - queue_manager - Skipping queue item: MUTUAL ENEMY
2021-08-24 09:11:55,657 - DEBUG - queue_manager - Skipping queue item: LEGENDARY BATTLE
2021-08-24 09:11:55,658 - DEBUG - queue_manager - Skipping queue item: DANGER ROOM
2021-08-24 09:11:55,659 - DEBUG - queue_manager - Skipping queue item: TIMELINE BATTLE
2021-08-24 09:11:55,660 - DEBUG - queue_manager - Skipping queue item: GOLDEN GODS
2021-08-24 09:11:55,664 - DEBUG - queue_manager - Skipping queue item: THE FAULT
2021-08-24 09:11:55,666 - DEBUG - queue_manager - Skipping queue item: TWISTED WORLD
2021-08-24 09:11:55,669 - DEBUG - queue_manager - Running WORLD BOSS with settings: {'mode': 'ULTIMATE', 'boss': 'TODAYS_BOSS', 'difficulty': 5, 'sync_character_and_ally_teams': True}
2021-08-24 09:11:56,500 - DEBUG - root - Creating 4 Tesseract API(s) with 'eng' language.
2021-08-24 09:11:56,807 - DEBUG - root - Creating 2 Tesseract API(s) with 'mff+eng' language.
2021-08-24 09:11:58,537 - DEBUG - game - Stage: THE FAULT; stages: 6/6
2021-08-24 09:11:58,547 - DEBUG - game - Stage: GOLDEN GODS; stages: 6/6
2021-08-24 09:11:58,560 - DEBUG - game - Stage: VEILED SECRET; stages: 14/4
2021-08-24 09:11:58,601 - DEBUG - game - Stage: TWISTED WORLD; stages: 6/6
2021-08-24 09:11:58,604 - DEBUG - game - Stage: WORLD EVENT; stages: 1 1
2021-08-24 09:11:58,612 - DEBUG - game - Stage: WORLD BOSS; stages: 5/5
2021-08-24 09:11:58,647 - DEBUG - game - Stage: MUTUAL ENEMY; stages: 181
2021-08-24 09:11:58,650 - DEBUG - game - Stage: THE BIG TWIN; stages: 6/6
2021-08-24 09:11:58,655 - DEBUG - game - Stage: SHADOWLAND; stages: 0/35
2021-08-24 09:11:58,659 - DEBUG - game - Stage: DIMENSION MISSION; stages: 1/7
2021-08-24 09:11:58,676 - DEBUG - game - Stage: LEGENDARY BATTLE; stages: 11 1
2021-08-24 09:11:58,703 - DEBUG - game - Stage: PLAYING HERO; stages: 1111
2021-08-24 09:11:58,784 - INFO - world_boss - 5 stages available, running ULTIMATE mode with difficulty = 5.
2021-08-24 09:12:04,926 - DEBUG - world_boss - World Boss Special Offer was closed: False
2021-08-24 09:12:06,190 - DEBUG - world_boss - World Boss Special Offer was closed: False
2021-08-24 09:12:07,459 - DEBUG - world_boss - World Boss Special Offer was closed: False
2021-08-24 09:12:11,073 - ERROR - world_boss - Can't find READY button after selecting the boss.
2021-08-24 09:12:12,682 - DEBUG - notifications - After mission notifications was closed: False
2021-08-24 09:12:13,801 - DEBUG - notifications - After mission notifications was closed: False
2021-08-24 09:12:14,920 - DEBUG - notifications - After mission notifications was closed: False
2021-08-24 09:12:16,120 - DEBUG - queue_manager - Queue was forcibly stopped.
2021-08-24 09:12:16,140 - DEBUG - queue_manager - Queue completed.`

**Comment by tmarenko** [comment] 2021-08-25 10:31
> I think WB is broken

Does it happen regularly?

**Comment by dbzdivik** [comment] 2021-08-25 11:53
> Does it happen regularly?

Yes I tried Sync and Non-Sync. All 5/5 Stages were avail, Manually leveled WB Ultimate Stage.
Still Same

**Comment by tmarenko** [comment] 2021-08-30 09:20
> Yes I tried Sync and Non-Sync. All 5/5 Stages were avail, Manually leveled WB Ultimate Stage.
Still Same

I can't reproduce this issue at 1080p/720p resolution. I'll need full log-file or video recording.
https://github.com/tmarenko/mff_auto/commit/588244a1de8458468304486db50b2b68fdb98e4d isn't the origin of the problem of this so if you still encounter the problem then create new issue for it.

**Comment by tmarenko** [comment] 2021-09-06 16:41
> Support team Selection in WB and EBR, Like team 1 is selected the Supporting team 1 is selected, and so on.

Released in https://github.com/tmarenko/mff_auto/releases/tag/0.8.10

**Closed by tmarenko** 2021-09-06 16:41 UTC
Labels: enhancement
