### ISSUE TITLE
General Bug

### ISSUE THREAD

**Issue by dbzdivik** [tmarenko/mff_auto#10] opened 2020-10-14 16:15 UTC
>2020-10-14 21:34:20,476 - epic_quests - INFO - No ally, restarting
2020-10-14 21:34:20,478 - game - DEBUG - Closing game.
2020-10-14 21:34:23,542 - game - DEBUG - Closing game.
2020-10-14 21:34:26,577 - game - DEBUG - Closing game.
2020-10-14 21:34:29,671 - game - DEBUG - Closing game.
2020-10-14 21:34:32,670 - game - DEBUG - Closing game.
2020-10-14 21:34:35,712 - game - DEBUG - Closing game.
2020-10-14 21:34:37,786 - game - DEBUG - Starting game.
2020-10-14 21:35:11,345 - game - DEBUG - Loading circle is on screen.
2020-10-14 21:35:22,958 - game - DEBUG - Loading circle is on screen.
2020-10-14 21:36:42,769 - game - WARNING - Failed to start game
2020-10-14 21:36:49,927 - missions - WARNING - Unable to press START button.
2020-10-14 21:36:49,928 - epic_quests - ERROR - Cannot start Epic Quest stage <lib.game.ui.Rect object at 0x13698870>, exiting.
2020-10-14 21:36:49,936 - epic_quests - INFO - No more stages for STUPID X-MEN.
2020-10-14 21:36:51,745 - missions - DEBUG - After mission notifications was closed: False
2020-10-14 21:36:52,817 - missions - DEBUG - After mission notifications was closed: False
2020-10-14 21:36:53,856 - missions - DEBUG - After mission notifications was closed: False
2020-10-14 21:36:56,877 - queue_manager - DEBUG - Running VEILED SECRET with settings: {}
2020-10-14 21:36:58,598 - root - DEBUG - Creating 4 Tesseract API(s) with 'eng' language.
2020-10-14 21:36:59,019 - root - DEBUG - Creating 2 Tesseract API(s) with 'mff+eng' language.
2020-10-14 21:37:03,702 - game - ERROR - Failed to open Content Status board.
2020-10-14 21:37:03,913 - queue_manager - DEBUG - Running THE BIG TWIN with settings: {}
2020-10-14 21:37:05,501 - root - DEBUG - Creating 4 Tesseract API(s) with 'eng' language.
2020-10-14 21:37:05,813 - root - DEBUG - Creating 2 Tesseract API(s) with 'mff+eng' language.
2020-10-14 21:37:10,219 - game - ERROR - Failed to open Content Status board.
2020-10-14 21:37:10,474 - queue_manager - DEBUG - Running LEGENDARY BATTLE with settings: {'mode': 'NORMAL', 'battle': 'CAPTAIN_MARVEL', 'stage': 'LB_BATTLE_STAGE_1'}
2020-10-14 21:37:12,096 - root - DEBUG - Creating 4 Tesseract API(s) with 'eng' language.
2020-10-14 21:37:12,409 - root - DEBUG - Creating 2 Tesseract API(s) with 'mff+eng' language.
2020-10-14 21:37:16,761 - game - ERROR - Failed to open Content Status board.
2020-10-14 21:37:16,972 - queue_manager - DEBUG - Skipping queue item: WORLD BOSS
2020-10-14 21:37:16,975 - queue_manager - DEBUG - Skipping queue item: WORLD BOSS INVASION
2020-10-14 21:37:16,976 - queue_manager - DEBUG - Running CO-OP PLAY with settings: {}
2020-10-14 21:37:18,633 - root - DEBUG - Creating 4 Tesseract API(s) with 'eng' language.
2020-10-14 21:37:18,952 - root - DEBUG - Creating 2 Tesseract API(s) with 'mff+eng' language.
2020-10-14 21:37:23,428 - game - ERROR - Failed to open Content Status board.
2020-10-14 21:37:23,641 - queue_manager - DEBUG - Running DANGER ROOM with settings: {'mode': 'NORMAL'}
2020-10-14 21:37:25,464 - root - DEBUG - Creating 4 Tesseract API(s) with 'eng' language.
2020-10-14 21:37:25,886 - root - DEBUG - Creating 2 Tesseract API(s) with 'mff+eng' language.
2020-10-14 21:37:30,360 - game - ERROR - Failed to open Content Status board.
2020-10-14 21:37:30,568 - queue_manager - DEBUG - Queue completed.

**Comment by tmarenko** [comment] 2020-10-15 17:36
Sure, the queue shouldn't be stopped even if we can't restart the game.
I've fixed in fa5364e7656c230db20879a670f9b9b724bd768f
So now if bot can't restart the game then it continue to complete mission as usual without farming bios.
Still there would be 3-4 min pause (awating for restart), but I think it's not a big deal because that is unexpected behavior.

**Closed** 2020-10-20 15:04 UTC
